### PR TITLE
Fixed terrain and geoObject shaders on Mac

### LINKED ISSUE #710: Fix jittering on MacPC

### PR DESCRIPTION
**Pull request by Zemledelec**

### CODE REVIEW

File: src/og/shaders/geoObject.js [hunk 1]
```diff
@@ -216,47 +212,58 @@ export const geo_object_picking = () =>
...
+                 // if(lookLength > uScaleByDistance[1])
+                 // {
+                 //     scd = uScaleByDistance[1] / uScaleByDistance[0];
+                 // }
+                 // else if(lookLength > uScaleByDistance[0])
+                 // {
+                 //     scd = lookLength / uScaleByDistance[0];
+                 // }
+                 // ... is the same math above
+                 // @hack
```
Comment (pavletto) [inline src/og/shaders/geoObject.js:257]: awesome comments and idea!
