### PR TITLE
Camera flight position fix

### LINKED ISSUE #892: camera fly easing is shaking if camera already near or exactly in destination
How to reproduce:
https://sandbox.openglobus.org/examples/cameraFly
- click on 'Fly point'
- wait for animation finish
- repeat 'Fly point'
you will observe little shake. situation going worse, on frequent clicking

### LINKED ISSUE #893: Camera animation refactor
Implement time based animation instead of frame based.
add EasingFunc support

### PR DESCRIPTION
**Pull request by Zuzon**
https://github.com/openglobus/openglobus/issues/892

### CODE REVIEW

**Review by Zemledelec — APPROVED** [review]
It is a good solution of the problem!

**Review by Zemledelec — APPROVED** [review]
Just to remember ground_a no ground anymore) is is start position

**Comment by Zemledelec** [comment]
Tested, unfortunately clone doesn't fix the problem/ Let's discuss.

**Review by Zemledelec — CHANGES_REQUESTED** [review]
Let's discuss more.

**Comment by Zuzon** [comment]
added camera events to handle mouse and touch navigation inertia

**Comment by Zuzon** [comment]
added easing functions and possibility to add custom easing function for animations

**Comment by Zuzon** [comment]
made time based animation for camera flight instead of frame based

File: src/camera/PlanetCamera.ts [hunk 1]
```diff
@@ -11,19 +11,56 @@ import {Vec3} from "../math/Vec3";
...
 import {RADIANS} from "../math";
+import { EventsHandler } from "../Events";
+import { Easing, EasingFunction } from "../utils/easing";
 
 export interface IPlanetCameraParams extends ICameraParams {
     minAltitude?: number;
     maxAltitude?: number;
 }
 
+export type PlanetCameraEventsList = [
```
Comment (Zemledelec) [inline src/camera/PlanetCamera.ts:22]: I suggest using `flystart`, `flyend`, and `flystop` instead. Event names usually follow lowercase naming conventions, and these options are also more concise.

File: src/control/MouseNavigation.ts [hunk 2]
```diff
@@ -145,6 +145,11 @@ export class MouseNavigation extends Control {
             this.renderer.events.on("keyfree", input.KEY_ALT, this._onShiftFree);
             this.renderer.events.on("keyfree", input.KEY_PRINTSCREEN, this._onShiftFree);
         }
+        if (this.planet?.camera) {
```
Comment (Zemledelec) [inline src/control/MouseNavigation.ts:151]: I think we also need to support a deactivate method. When the navigation control is deactivated, we should call `this.planet.camera.events.off("...")` to stop handling camera fly stop events.

File: src/utils/easing.ts [hunk 3]
```diff
@@ -0,0 +1,106 @@
+export type EasingFunction = (t: number) => number;
+
+export class Easing {
```
Comment (Zemledelec) [inline src/utils/easing.ts:3]: This is wonderful, man! @Zuzon

**Review by Zemledelec — CHANGES_REQUESTED** [review]
Great solution, @Zuzon! Let me test it. I suggested changing the event names - check them out, and if you don’t like them, let’s discuss. Always open!

**Review by Zemledelec — COMMENTED** [review]
Testing

File: src/camera/PlanetCamera.ts [hunk 4]
```diff
@@ -348,15 +391,19 @@ class PlanetCamera extends Camera {
...
-        frameCallback?: Function | null) {
+        frameCallback?: Function | null,
+        duration: number = DEFAULT_FLIGHT_DURATION,
+        ease: EasingFunction = DEFAULT_EASING) {
         this.flyCartesian(
             this.getExtentPosition(extent, height),
             Vec3.ZERO,
             up,
             ampl == null ? 1 : ampl,
             completeCallback,
```
Comment (Zemledelec) [inline src/camera/PlanetCamera.ts:407]: May be replace this input parameters before callbacks, as more valuable?
        duration: number = DEFAULT_FLIGHT_DURATION,
        ease: EasingFunction = DEFAULT_EASING

otherwise it looks like

    globus.planet.camera.flyLonLat(destPos, lookCart, upVec, null, null, null, null, 5000);

**Review by Zemledelec — CHANGES_REQUESTED** [review]

File: src/camera/PlanetCamera.ts (hunk 4 above)
Comment (Zemledelec) [reply src/camera/PlanetCamera.ts:407]: Also, let's make jsdoc for the methods parameters too.

**Review by Zemledelec — CHANGES_REQUESTED** [review]
Add jsodoc, and the question if you think ok, to replace duration and easing before callbacks.

**Review by Zemledelec — APPROVED** [review]
