### PR TITLE
Wms 1.3.0 bbox claculation

### LINKED ISSUE #954: WMS version 1.3.0
When requesting WMS layers with version 1.3.0, the rendering is incorrect (see example: https://codesandbox.io/p/devbox/morning-mountain-4hcv3v).

I believe this is because the BBOX calculation for v1.3.0 is currently the same for all projection types, even those without swapped axes (https://github.com/openglobus/openglobus/blob/master/src/layer/WMS.ts#L129)

I have implemented a fix in my fork where I imported a list of EPSG codes of projections with swapped axes ( from https://github.com/EOxServer/eoxserver/blob/master/eoxserver/resources/coverages/crss.py#L49). I now apply the swapped axis logic only if the code is present in this list.

I have edited the sandbox OSM example, and the correct tiles are now being requested.
[my fork](https://github.com/baloola/openglobus/tree/wms-bbox)
Could I open PR for this ?

### PR DESCRIPTION
**Pull request by baloola**
This PR optimizes WMS 1.3.0 layer tile requests by correcting BBOX calculations. Previously, certain projections resulted in requests for the wrong tiles.

Related issue: #954

### Current Behaviour:
Requesting the layer below—where the projection of the GetMap request is EPSG:4326—requests the wrong tiles (incorrect axis order: minY, minX, maxY, maxX).
```ts
var ne = new WMS("Natural Earth", {
        visibility: true,
        isBaseLayer: false,
        url: 'https://services.sentinel-hub.com/ogc/wms/0635c213-17a1-48ee-aef7-9d1731695a54',
        layers: 'AWS_NO2-VISUALISATION',
        version: '1.3.0',
        opacity: 0.7,
        extra: {
            transparent: true
        }
    });
```
Screenshot from 2025-12-14 17-35-51

### FIX

This fix provides a list of EPSG codes that require axis swapping. The code now only applies the swapped x/y BBOX calculation if the projection is in this list, which results in the correct tiles being requested.

Axis swapping could be determined dynamically (by reading the projection's proj4 definition and if axis orientation is `+axis=neu`), but I think that this implementation would need third-party dependencies.

Applying this fix generates the correct requests:

Screenshot from 2025-12-14 17-27-09

### CODE REVIEW

**Comment by baloola** [comment]
Looking more thoroughly at the segmentation logic, it looks like the extent of the WMS requests is always calculated in either `EPSG:4326` or `EPSG:3857`, which means that the bbox coordinates would always be in one of the two projections.

This simply means that the projections list is not required/supported, and that logic would be to swap the coordinates in the case of `EPSG:4326`, otherwise use (minx, miny, maxx, maxy).

Therefore, there should probably be a mention in the docs that for WMS layers, only (EPSG:4326 and EPSG:3857) are supported in OpenGlobus.

File: src/layer/WMS.ts [hunk 1]
```diff
@@ -125,9 +125,12 @@ class WMS extends XYZ {
         return `${extent.getWest()},${extent.getSouth()},${extent.getEast()},${extent.getNorth()}`;
     }
 
-    static get_bbox_v1_3_0(extent: Extent): string {
+    static get_bbox_v1_3_0(extent: Extent, srs: string): string {
+        if (srs === "epsg:4326") {
         return `${extent.getSouth()},${extent.getWest()},${extent.getNorth()},${extent.getEast()}`;
     }
+    return `${extent.getWest()},${extent.getSouth()},${extent.getEast()},${extent.getNorth()}`;
```
Comment (Zuzon) [inline src/layer/WMS.ts]: some code formatting would be great

File: src/layer/WMS.ts [hunk 2]
```diff
@@ -125,9 +125,12 @@ class WMS extends XYZ {
         return `${extent.getWest()},${extent.getSouth()},${extent.getEast()},${extent.getNorth()}`;
     }
 
-    static get_bbox_v1_3_0(extent: Extent): string {
+    static get_bbox_v1_3_0(extent: Extent, srs: string): string {
```
Comment (Zemledelec) [inline src/layer/WMS.ts:128]: This is bug fixer! Thank you @baloola!

Please, correct spaces.

Foir future just wold be nice also to have something like

```
const LATLON_ORDER = new Set([
  "epsg:4326",
  // etc
])
```

...and then 
```
const code = srs.toLowerCase();
if (LATLON_ORDER.has(code)) {
```

**Review by Zemledelec — CHANGES_REQUESTED** [review]
Please correct spaces after if.

**Review by Zemledelec — APPROVED** [review]

**Comment by Zemledelec** [comment]
Welcome to contributors @baloola! :)
