### PR TITLE
#974-Adds-UI-exports

### LINKED ISSUE #974: Unable to import UI components
We are building some custom controls and would like to leverage the existing code in `/ui` but are unable to import them.

vite: 7.0.4
@openglobus/og: 0.28.6

```
import { Button, IButtonParams } from '@openglobus/og/lib/ui/Button';
```

Returns the error: 
```
Missing "./lib/ui/Button" specifier in "@openglobus/og" package
```

I'd like to propose adding those exports

### PR DESCRIPTION
**Pull request by ChrisLowe-Takor**
Adds the ability to import UI classes in a vite project

Fixes: #974

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -108,6 +109,7 @@ export {
     mars,
     terrain,
     layer,
+    ui,
```
Comment (Zemledelec) [inline src/index.ts:112]: Nice!

**Review by Zemledelec — APPROVED** [review]
