### PR TITLE
#694 Fixed geoimage setsrc

### LINKED ISSUE #694: geoImage setSrc() not working
The geoImage has a function to change the source of the texture:

https://github.com/openglobus/openglobus/blob/3775233c77b5304c64ca1faed26945cec55413b0/src/og/layer/GeoImage.js#L47

But this does not seem to function as expected. I would expect the geoImage layer to update with the new Image url as source?

I have made a codePen showing the issue:

https://codepen.io/program-sam/pen/QWZMZmO

### PR DESCRIPTION
**Pull request by Zemledelec**

### CODE REVIEW

File: src/og/utils/shared.js [hunk 1]
```diff
@@ -958,4 +958,8 @@ export async function loadImage(url) {
         image.src = url;
         return image;
     });
+}
+
+export function isImageLoaded(image) {
```
Comment (pavletto) [inline src/og/utils/shared.js:968]: Add documentation

File: src/og/layer/GeoImage.js [hunk 2]
```diff
@@ -57,9 +63,16 @@ class GeoImage extends BaseGeoImage {
      */
```
Comment (pavletto) [inline src/og/layer/GeoImage.js:63]: and documentation here

**Review by pavletto — APPROVED** [review]
