### PR TITLE
870

### LINKED ISSUE #870: TouchNavigation is broken
Not completely but needs to be improved.

### PR DESCRIPTION
**Pull request by Zuzon**
Touch navigation:
tilt limit set.
zoom speed limit added to prevent unexpectedly fast zoom with multitouch (when fingers are set too close to each other)

### CODE REVIEW

File: src/control/TouchNavigation.ts [hunk 1]
```diff
@@ -303,7 +302,8 @@ export class TouchNavigation extends Control {
 
                 const zoomCur = t0.vec.sub(t1.vec);
                 const zoomPrev = t0.vecPrev.sub(t1.vecPrev);
-                const scale = zoomCur.length() / zoomPrev.length();
+                let scale = zoomCur.length() / zoomPrev.length();
+                scale = scale > 1.08 ? 1.08 : scale < 0.92 ? 0.92 : scale;
```
Comment (Zuzon) [inline src/control/TouchNavigation.ts:306]: these magic numbers are the actual zoom speed limiters. Values are found as most optimal from UX perspective.
Normally (by code conduct) it should be configurable, but i'm not sure is it really required here

Comment (Zemledelec) [reply src/control/TouchNavigation.ts:306]: understand, ok

File: src/camera/PlanetCamera.ts [hunk 2]
```diff
@@ -551,10 +551,9 @@ class PlanetCamera extends Camera {
 
         let eyeNorm = eye.getNormal();
         let slope = b.dot(eyeNorm);
-
+        if (u.dot(eyeNorm) <= 0) return;
```
Comment (Zemledelec) [inline src/camera/PlanetCamera.ts:554]: good!

**Review by Zemledelec — APPROVED** [review]
